---
title: "Results CIBERSORT"
output: 
  github_document:
     toc: true
     toc_depth: 2
bibliography: citations.bib  
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r include=FALSE}
library(here)
library(ggplot2)
library(cowplot)
library(tidyr)
library(dplyr)
```

# CIBERSORT

```{r Read in metadata}
metadata <- read.csv(file = here("intermediate_files/metadata/reformat_samples_extra_info.csv"))
colnames(metadata)[1] <- "Mixture"
metadata$Mixture <- as.character(metadata$Mixture)
metadata$Condition <- ifelse(metadata$Condition == "Tumour", "CAF", "TAN")
```

## CIBERSORT results online

```{r echo=FALSE}
cibersort_output <- read.csv(here("intermediate_files/cibersort/CIBERSORTx_Job14_Results.csv"))
cibersort_output$Mixture <- gsub(pattern = "X", replacement = "", x = cibersort_output$Mixture)
```

```{r echo=FALSE}
cibersort_results_long_online <- pivot_longer(cibersort_output, cols = c(S1, S3, S4), names_to = "Subpopulation")
cibersort_results_long_online$Mixture <- as.character(cibersort_results_long_online$Mixture)
cibersort_plot_online <- ggplot(cibersort_results_long_online, 
                                aes(x = as.character(Mixture), y = value, fill = Subpopulation)) +
  geom_col() + 
  ggtitle("CIBERSORT results online") +   
  theme(plot.title = element_text(hjust = 0.5),  axis.text = element_text(size = 8, angle = 90)) +
  xlab("Mixture") + 
  ylab("Proportion") +
  theme(#panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1.0000001)) 
```

```{r}
cibersort_plot_online
```

```{r echo=FALSE}
outfile.plot.name <-  paste("outfiles/cibersort_results_online_", Sys.Date(), ".png", sep = "")
ggsave(filename = here(outfile.plot.name), plot = cibersort_plot_online)
```

```{r echo=FALSE}
print(paste("saved to ...", outfile.plot.name))
```

## CIBERSORT results docker

```{r echo=FALSE}
cibersort_output_docker <- read.table(here("intermediate_files/cibersort/outputs/CIBERSORTx_Results.txt"), header = T)
cibersort_output_docker$Mixture <- gsub(pattern = "X", replacement = "", x = cibersort_output_docker$Mixture)
```

```{r echo=FALSE}
cibersort_results_long_docker <- pivot_longer(cibersort_output_docker, cols = c(S1, S3, S4), names_to = "Subpopulation")
cibersort_results_long_docker$Mixture <- as.character(cibersort_results_long_docker$Mixture)
cibersort_plot_docker <- ggplot(cibersort_results_long_docker, 
                                aes(x = as.character(Mixture), y = value, fill = `Subpopulation`)) +
  geom_col() + 
  ggtitle("CIBERSORT results Docker") +   
  theme(plot.title = element_text(hjust = 0.5),  axis.text = element_text(size = 8, angle = 90)) +
  xlab("Mixture") + 
  ylab("Proportion") +
  theme(#panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1.0000001)) 
```

```{r}
cibersort_plot_docker
```

```{r echo=FALSE}
outfile.plot.name.docker <-  paste("outfiles/cibersort_results_docker_", Sys.Date(), ".png", sep = "")
ggsave(filename = here(outfile.plot.name.docker), plot = cibersort_plot_docker)
```

```{r echo=FALSE}
print(paste("saved to ...", outfile.plot.name.docker))
```

```{r, include = FALSE}
legend <- get_legend(
  # create some space to the left of the legend
  cibersort_plot_docker + 
    theme(legend.box.margin = margin(0, 0, 0, 12),
          legend.key.size = unit(0.5, 'cm'),
          legend.key.height = unit(0.5, 'cm'),
          legend.key.width = unit(0.5, 'cm'),
          legend.title = element_text(size=8),
          legend.text = element_text(size=8)
          )
)
cibersort_grid <- plot_grid(cibersort_plot_online + theme(legend.position = "none"),
                            cibersort_plot_docker + theme(legend.position = "none"),
                             ncol = 2,
      labels = c('A', 'B'),
      label_fontfamily = 'serif',
      label_fontface = 'bold',
      label_size = 15,
      align = 'h')
cibersort_grid <- plot_grid(cibersort_grid, legend, rel_widths = c(3,.5))
outfile.plot.name.combined <-  paste("outfiles/cibersort_plot_combined_batch_corrected_", Sys.Date(), ".png", sep = "")
ggsave(filename = here(outfile.plot.name.combined), 
       plot = cibersort_grid,
       width = 20,
       height = 10,
       units = "cm")
```

```{r CIBERSORT plots}
cibersort_grid
```

```{r echo=FALSE}
print(paste("saved to ...", outfile.plot.name.combined))
```

## Separate plot per subpopulation, using online version of CIBERSORT


```{r S1 plot}
cibersort_output_metadata <- full_join(cibersort_output, metadata, by = "Mixture")
ggplot(cibersort_output_metadata, 
                                aes(x = as.character(Mixture), y = S1, fill = Condition
)) +
  geom_col() + 
  ggtitle("CIBERSORT results S1") +   
  theme(plot.title = element_text(hjust = 0.5),  axis.text = element_text(size = 8, angle = 90)) +
  xlab("Mixture") + 
  ylab("Proportion") +
  theme(#panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1.0000001)) 

```

```{r S3 plot}
ggplot(cibersort_output_metadata, 
                                aes(x = as.character(Mixture), y = S3, fill = Condition
)) +
  geom_col() + 
  ggtitle("CIBERSORT results S3") +   
  theme(plot.title = element_text(hjust = 0.5),  axis.text = element_text(size = 8, angle = 90)) +
  xlab("Mixture") + 
  ylab("Proportion") +
  theme(#panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1.0000001)) 

```

```{r S4 plot}
ggplot(cibersort_output_metadata, 
                                aes(x = as.character(Mixture), y = S4, fill = Condition
)) +
  geom_col() + 
  ggtitle("CIBERSORT results S4") +   
  theme(plot.title = element_text(hjust = 0.5),  axis.text = element_text(size = 8, angle = 90)) +
  xlab("Mixture") + 
  ylab("Proportion") +
  theme(#panel.grid.major = element_blank(), 
        panel.grid.minor = element_blank(),
        panel.background = element_blank(), 
        axis.line = element_line(colour = "black")) +
      scale_y_continuous(expand = c(0, 0), limits = c(0, 1.0000001)) 

```
### Line Plots

```{r}
library("ggpubr")
ggline(cibersort_output_metadata, x = "Condition", y = "S1", 
       add = c("median", "jitter"), 
          order = c("TAN", "CAF"),
          ylab = "Proportion", xlab = "Condition",
       title = "Line plot TAN CAF proportions S1\n Median marked")

ggline(cibersort_output_metadata, x = "Condition", y = "S3", 
       add = c("median", "jitter"), 
          order = c("TAN", "CAF"),
          ylab = "Proportion", xlab = "Condition",
       title = "Line plot TAN CAF proportions S3\n Median marked")

ggline(cibersort_output_metadata, x = "Condition", y = "S4", 
       add = c("median", "jitter"), 
          order = c("TAN", "CAF"),
          ylab = "Proportion", xlab = "Condition",
       title = "Line plot TAN CAF proportions S4\n Median marked")

```

```{r Plot paired data}

# Subset weight data before treatment
#TAN <- subset(cibersort_output_metadata,  Condition == "TAN", S1,
            #     drop = TRUE)
# subset weight data after treatment
#CAF <- subset(cibersort_output_metadata,  group == "after", weight,
               #  drop = TRUE)
# Plot paired data
#library(PairedData)
#pd <- paired(before, after)
#plot(pd, type = "profile") + theme_bw()
```


### Significance tests


```{r Test for normality}
shapiro.test(cibersort_output_metadata$S1)
shapiro.test(cibersort_output_metadata$S3)
shapiro.test(cibersort_output_metadata$S4)

```

```{r}
group_by(cibersort_output_metadata, Condition) %>%
  summarise(
    count = n(),
    median = median(S1, na.rm = TRUE),
    IQR = IQR(S1, na.rm = TRUE)
  )

group_by(cibersort_output_metadata, Condition) %>%
  summarise(
    count = n(),
    median = median(S3, na.rm = TRUE),
    IQR = IQR(S3, na.rm = TRUE)
  )

group_by(cibersort_output_metadata, Condition) %>%
  summarise(
    count = n(),
    median = median(S4, na.rm = TRUE),
    IQR = IQR(S4, na.rm = TRUE)
  )
```

```{r}
s1.test <- wilcox.test(S1 ~ Condition, data = cibersort_output_metadata, paired = TRUE)$p.value
s3.test <- wilcox.test(S3 ~ Condition, data = cibersort_output_metadata, paired = TRUE)$p.value
s4.test <- wilcox.test(S4 ~ Condition, data = cibersort_output_metadata, paired = TRUE)$p.value
p.values <- c(s1.test, s3.test, s4.test)
wilcox_results <- data.frame(Subpopulation = c("S1", "S3", "S4"), p.value = p.values, p.adj = p.adjust(p.values, method = "bonferroni"))
wilcox_results
```

We can see that there might be a difference in S4 proportions between CAF and TANs, but that it is not statistically significant using a paired Wilcoxon signed rank test.
